apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/sandeep-soorya-kumar/MCP-For-Beginners.git
  name: MCP-For-Beginners
