apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-monitoring-alertmanager
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: 'alertmanager@localhost'
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'
        group_wait: 5s
        repeat_interval: 30m
      - match:
          severity: warning
        receiver: 'warning-alerts'
        group_wait: 30s
        repeat_interval: 2h
    
    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://localhost:5004/webhook'
        send_resolved: true
    
    - name: 'critical-alerts'
      webhook_configs:
      - url: 'http://localhost:5004/webhook'
        send_resolved: true
    
    - name: 'warning-alerts'
      webhook_configs:
      - url: 'http://localhost:5004/webhook'
        send_resolved: true
    
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']
