apiVersion: v1
kind: Secret
metadata:
  name: github-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/sandeep-soorya-kumar/MCP-For-Beginners.git
  # For public repositories, no authentication is needed
  # For private repositories, you would add:
  # username: your-github-username
  # password: your-github-token
