apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Enable webhook support
  server.insecure: "true"
  # Allow webhook access
  server.enable.grpc.web: "true"
  # Allow insecure repositories
  reposerver.insecure: "true"
