apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-test
  namespace: default
  labels:
    app: cpu-stress-test
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  containers:
  - name: cpu-stress
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Generating CPU load...'; done"]
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
  restartPolicy: Never
