apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-auto-heal.fullname" . }}
  labels:
    {{- include "k8s-auto-heal.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "mcp" }}
      protocol: TCP
      name: mcp
    - port: 8080
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "k8s-auto-heal.selectorLabels" . | nindent 4 }}
