replicaCount: 1
image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: latest
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 48600m
    memory: 256Mi
  requests:
    cpu: 14580m
    memory: 128Mi

autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
cpuStress:
  enabled: true
  intensity: 100
  duration: 60
  # Force ArgoCD cache refresh
