apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cpu-stress-app.fullname" . }}
  labels:
    {{- include "cpu-stress-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cpu-stress-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cpu-stress-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cpu-stress-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.cpuStress.enabled }}
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "Starting CPU stress test with intensity: {{ .Values.cpuStress.intensity }}% for {{ .Values.cpuStress.duration }} seconds"
              while true; do
                # Create CPU load using dd and /dev/zero
                dd if=/dev/zero of=/dev/null bs=1M count=1000 &
                sleep {{ .Values.cpuStress.duration }}
                # Kill the dd process to stop CPU stress
                pkill dd || true
                sleep 10
              done
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}